name: Build and Deploy Frontend

on:
  push:
    paths:
      - .github/workflows/frontend.yaml
      - 'docker/Dockerfile.frontend'
      - 'apps/frontend/**'  
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Confirm Docker login
        run: |
          echo "Docker login test:"
          docker info
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ring0exec/cloud-vector-frontend:${{ github.sha }}

      - name: Clone gitops repo, update, and push
        env:
          PAT: ${{ secrets.CLOUD_VECTOR_GITOPS_TOKEN }}
        run: |
          git clone https://github.com/Torque-Lab/cloud-infra-ops.git
          cd cloud-infra-ops
          
          sed -i "/frontend:/,/^[^ ]/s/^\(\s*tag:\s*\).*/\1${{ github.sha }}/" apps/internal-charts/frontend/values.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git diff --quiet || {
            git add apps/internal-charts/frontend/values.yaml
            git commit -m "Update frontend image to ${{ github.sha }}"
            git push https://${PAT}@github.com/Torque-Lab/cloud-infra-ops.git main  --force
          }