
name: Build and Deploy Https Server

on:
  push:
    paths:
      - .github/workflows/https-server.yaml
      - 'docker/Dockerfile.https-server'
      - 'apps/https-server/**'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.https-server
          push: true
          tags: ring0exec/cloud-vector-https-server:${{ github.sha }}

      - name: Clone gitops repo, update, and push
        env:
          PAT: ${{ secrets.CLOUD_VECTOR_GITOPS_TOKEN }}
        run: |
          git clone https://github.com/Torque-Lab/cloud-infra-ops.git
          cd cloud-infra-ops
          ls apps/internal-charts/https-server/
          cat apps/internal-charts/https-server/values.yaml
          sed -i "/httpsServer:/,/^[^ ]/s/^\(\s*tag:\s*\).*/\1${{ github.sha }}/" apps/internal-charts/https-server/values.yaml
        
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

            git diff --quiet || {
            git add apps/internal-charts/https-server/values.yaml
            git commit -m "Update https-server image to ${{ github.sha }}"
            git push https://${PAT}@github.com/Torque-Lab/cloud-infra-ops.git main --force
          }

          
          